name: contribute
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.15.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^1.10.6
  firebase_auth: ^3.3.4
  google_sign_in: ^5.2.1
  cloud_firestore: ^3.1.5
  provider: ^6.0.1
  keyboard_dismisser: ^2.0.0
  fluttertoast: ^8.0.8
  flutter_svg: ^1.0.0
  http: ^0.13.4
  flutter_native_splash: ^1.3.3
  flutter_launcher_icons: ^0.9.2
  url_launcher: ^6.0.17
  dotted_border: ^2.0.0+2

  cupertino_icons: ^1.0.2

flutter_native_splash:
  color: '#3E2C41'
  image: 'assets/main-logo.png'
  android: true
  ios: true
  web: true

flutter_icons:
  image_path: 'assets/idea-logo.png'
  android: true
  ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
